
const Images = {
  background: require('../assets/images/background.png'),
  logo: require('../assets/images/logo.png'),
  lock: require('../assets/images/lock.png'),
  wallet: require('../assets/images/wallet.png'),
  pin_fill_icon: require('../assets/images/ic_pin_fill.png'),
  reload: require('../assets/images/reload.png'),
  wallet_frame: require('../assets/images/wallet_frame.png'),
  eth: require('../assets/images/eth.png'),
  bitcoin: require('../assets/images/bitcoin.png'),
  tick: require('../assets/images/tick.png'),
  tick: require('../assets/images/tick.png'),
  me: require('../assets/images/me_tab.png'),
  earn_reward: require('../assets/images/earn_reward_tab.png'),
  discover: require('../assets/images/discover_tab.png'),
  market: require('../assets/images/market_tab.png'),
  myassets: require('../assets/images/wallet_tab.png'),
  wallet_add: require('../assets/images/wallet_add.png'),
  notification: require('../assets/images/notification.png'),
  conversion: require('../assets/images/conversion.png'),
  eye_open: require('../assets/images/eye_open.png'),
  eye_close: require('../assets/images/eye_close.png'),
  calculator: require('../assets/images/caculator.png'),
  swap: require('../assets/images/swap.png'),
  news: require('../assets/images/news.png'),
  icon_search: require('../assets/images/search.png'),
  btc: require('../assets/images/btc.png'),
  usdt: require('../assets/images/usdt.png'),
  increase: require('../assets/images/increase.png'),
  decrease: require('../assets/images/decrease.png'),
  scanner: require('../assets/images/scanner.png'),
  send: require('../assets/images/send.png'),
  more: require('../assets/images/more.png'),
  demo: require('../assets/images/demo.png'),
  close: require('../assets/images/close.png'),
  backButton: require('../assets/images/backButton.png'),
  copyButton: require('../assets/images/copyButton.png'),
  ic_scan_qr: require('../assets/images/ic_scan_qr.png'),

  ic_receive: require('../assets/images/ic_receive.png'),
  ic_scan: require('../assets/images/ic_scan.png'),
  ic_send: require('../assets/images/ic_send.png'),
  addToken: require('../assets/images/addToken.png'),
  ic_stake: require('../assets/images/ic_stake.png'),
  ic_swap: require('../assets/images/ic_swap.png'),

  ic_info: require('../assets/images/ic_info.png'),
  ic_line_chart: require('../assets/images/ic_line_chart.png'),
  ic_reload_tran: require('../assets/images/ic_reload_tran.png'),
  ic_transaction_swap: require('../assets/images/ic_transaction_swap.png'),
  ic_no_transaction: require('../assets/images/ic_no_transaction.png'),
  ic_scan_button: require('../assets/images/ic_scan_button.png'),
  ic_arrow_right: require('../assets/images/ic_arrow_right.png'),
  welcome_text: require('../assets/images/welcome_text.png'),
  kissan_text: require('../assets/images/kissan_text.png'),
  create_wallet_btn: require('../assets/images/create_wallet_btn.png'),
  import_wallet_btn: require('../assets/images/import_wallet_btn.png'),
  hot_wallet_text: require('../assets/images/hot_wallet_text.png'),
  ic_more_option: require('../assets/images/ic_more_option.png'),
  ic_tick: require('../assets/images/ic_tick.png'),
  ic_untick: require('../assets/images/ic_untick.png'),
  wallet_manage: require('../assets/images/wallet_manage.png'),
  back: require('../assets/images/back.png'),
  language: require('../assets/images/language.png'),
  Currency_list: require('../assets/images/Currency_list.png'),
  message: require('../assets/images/message.png'),
  security: require('../assets/images/security.png'),
  logout: require('../assets/images/logout.png'),
};

export default Images;
