import {StyleSheet} from 'react-native';
import {Fonts, colors} from '../../../theme';

export default StyleSheet.create({
  scanView: {
    backgroundColor: colors.white,
    paddingHorizontal: 15,
    paddingVertical: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  inputView: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    backgroundColor: colors.address_bg,
    marginTop: 15,
    paddingHorizontal: 5,
    alignItems: 'center',
    borderRadius: 10,
  },
  recentText: {
    fontWeight: '400',
    fontSize: 11,
    lineHeight: 22,
    fontFamily: Fonts.regular,
    color: colors.black,
  },
  recentActiveText: {
    borderBottomWidth: 3,
    color: colors.green,
    borderColor: colors.green,
  },
  amountText: {
    fontWeight: '500',
    fontFamily: Fonts.regular,
    fontSize: 14,
    color: colors.black,
  },
  amountInputText: {
    marginTop: 20,
    // height: 40,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: '#EDEDED',
    backgroundColor: colors.white,
    borderRadius: 5,
    color: colors.text_blue,
    fontSize: 22,
    textAlign: 'center',
    fontWeight: '700',
    fontFamily: Fonts.regular,
  },
  balanceText: {
    marginTop: 8,
    color: colors.balance_clr,
    fontFamily: Fonts.regular,
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  tabStyle: {
    height: 53,
    backgroundColor: colors.tabBackground,
    width: '100%',
    marginTop: 15,
    borderRadius: 50,
    borderColor: '#EDEDED',
    borderWidth: 1,
    padding: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tabItem: {
    flex: 1,
    borderRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noteText: {
    fontFamily: Fonts.regular,
    fontSize: 12,
    fontWeight: '500',
    color: colors.black,
  },
  noteTextView: {
    height: 150,
    borderColor: colors.box_grey,
    borderRadius: 5,
    borderWidth: 1,
    width: '100%',
    marginTop: 7,
    textAlignVertical: 'top',
    paddingHorizontal: 15,
    paddingVertical: 10,
    fontFamily: Fonts.regular,
    fontSize: 12,
    fontWeight: '400',
  },
  // =================== MODAL ==============
  conModalView: {
    backgroundColor: colors.white,
    height: '75%',
    alignItems: 'center',
    marginHorizontal: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    // paddingHorizontal: 15,
  },
  conTextView: {
    marginTop: 15,
    fontFamily: Fonts.regular,
    fontSize: 15,
    color: colors.black,
  },
  walletNameView: {
    marginTop: 15,
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 15,
  },
  walletNameText: {
    fontFamily: Fonts.regular,
    fontSize: 12,
    color: colors.black,
  },

  toFromText: {
    fontFamily: Fonts.regular,
    fontSize: 13,
    color: colors.black,
    fontWeight: '500',
  },
  conAddText: {
    fontFamily: Fonts.regular,
    fontSize: 11,
    color: '#989898',
    fontWeight: '500',
    marginTop: 4,
  },
  toFromView: {
    backgroundColor: '#F6F6F6',
    width: '47%',
    paddingVertical: 10,
    paddingHorizontal: 5,
  },
  toFromMainView: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
});
